### ISSUE TITLE
A simple web app to keep track of money

### ISSUE THREAD

**Issue by Welf06** [lovishprabhakar/C-Simplify#11] opened 2022-10-01 14:32 UTC
> Would have a simple interface of adding money and removing it
> If it would be useful, other features like transaction history and notes (like why they did that transaction) can be added

**Comment by Welf06** [comment] 2022-10-01 14:32
If this issue is approved I hope, it gets assigned to me :)

**Comment by lovishprabhakar** [comment] 2022-10-01 14:37
Go ahead @Welf06!

**Comment by lovishprabhakar** [comment] 2022-10-02 07:47
Don't forget to star the repository :)

**Comment by lovishprabhakar** [comment] 2022-10-02 17:21
@Welf06 updates?

**Comment by Welf06** [comment] 2022-10-03 13:25
@lovishprabhakar sorry my health has not been good, I will start working on this soon, but if you want to assign it someone else that is fine too

**Comment by lovishprabhakar** [comment] 2022-10-03 13:31
@Welf06 The issue is yours and will stay that way, but as per the protocol, I'll have to close it for now. You can open it later when you're good to work :)
I wish you a speedy recovery!

**Closed by lovishprabhakar** 2022-10-03 13:31 UTC
Labels: hacktoberfest-2022, hacktoberfest-accepted
